algoritmo "ex"
var
 n1, n2: real
inicio
      escreva ("Digite o primeiro valor: ")
      leia (n1)
      escreva ("Digite o segundo valor: ")
      leia (n2)
      se n1 > n2 entao
      escreva ("O primeiro valor é o maior")
      fimse
      se n1 < n2 entao
      escreva ("O segundo valor é o maior")
      fimse
      se n1 = n2 entao
      escreva ("O nenhum valor é o maior")
      fimse
fimalgoritmo